export const ActionTypes = {
    FETCH_CATEGORIES : "FETCH_CATEGORIES",
    FETCH_SUB_CATEGORIES : "FETCH_SUB_CATEGORIES",
    FETCH_PERCENT : "FETCH_PERCENT",
    UPDATE_PERCENT : "UPDATE_PERCENT",
    FETCH_SLIDERS : "FETCH_SLIDERS",
    ADD_SLIDER : "ADD_SLIDER",
    ADD_USER: "ADD_USER",
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    FETCH_STORES : "FETCH_STORES",
    FETCH_SINGLE_STORE : "FETCH_SINGLE_STORE",
    ERROR_MESSAGE : "ERROR_MESSAGE",
    SUCCESS_MESSAGE : "SUCCESS_MESSAGE",
    CATEGORY_CLEAN_UP : "CATEGORY_CLEAN_UP"
    
}