export const ActionTypes = {
    FETCH_CATEGORIES : "FETCH_CATEGORIES",
    FETCH_SUB_CATEGORIES : "FETCH_SUB_CATEGORIES",
    FETCH_PERCENT : "FETCH_PERCENT",
    UPDATE_PERCENT : "UPDATE_PERCENT",
    FETCH_SLIDERS : "FETCH_SLIDERS",
    ADD_SLIDER : "ADD_SLIDER",
    ADD_USER: "ADD_USER",
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    
}